packages:
  - 'apps/*'
  - 'libs/*'
  - 'e2e/*'
  - 'perf/*'
ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - 'nestjs-pino'
  - 'nx'
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - 'prisma'
