services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3,sqs,dynamodb
      - AWS_DEFAULT_REGION=eu-central-1
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - '4566:4566'
    volumes:
      - './docker/localstack/init-scripts:/etc/localstack/init/ready.d/init-aws.sh' # ready hook
