services:
  redis:
    image: redis:8-alpine
    ports:
      - '6379:6379'

  db:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app
